### ISSUE TITLE
which version of eigen should be build with ?

### ISSUE THREAD

**Issue by SeekPoint** [clab/att-coref#2]
now, I had done:
hg clone https://bitbucket.org/eigen/eigen
hg checkout 3.0.0

then 
cmake -DEIGEN3_INCLUDE_DIR=/home/rzai/prj/eigen ..
make

I got the error:
rzai@rzai00:~/prj/att-coref/build$ make -j4
Scanning dependencies of target cnn
Scanning dependencies of target cnn_shared
[  1%] [  3%] [  5%] Building CXX object cnn/cnn/CMakeFiles/cnn.dir/cfsm-builder.cc.o
Building CXX object cnn/cnn/CMakeFiles/cnn.dir/cnn.cc.o
Building CXX object cnn/cnn/CMakeFiles/cnn.dir/conv.cc.o
[  6%] Building CXX object cnn/cnn/CMakeFiles/cnn_shared.dir/cfsm-builder.cc.o
In file included from /home/rzai/prj/eigen/Eigen/Core:35:0,
                 from /home/rzai/prj/eigen/Eigen/Dense:1,
                 from /home/rzai/prj/eigen/Eigen/Eigen:1,
                 from /home/rzai/prj/att-coref/cnn/cnn/tensor.h:21,
                 from /home/rzai/prj/att-coref/cnn/cnn/cnn.h:13,
                 from /home/rzai/prj/att-coref/cnn/cnn/cnn.cc:1:
/home/rzai/prj/eigen/Eigen/src/Core/util/Macros.h:252:35: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
 #define EIGEN_ASM_COMMENT(X)  asm("#"X)
                                   ^
In file included from /home/rzai/prj/eigen/Eigen/Core:35:0,
                 from /home/rzai/prj/eigen/Eigen/Dense:1,
                 from /home/rzai/prj/eigen/Eigen/Eigen:1,
                 from /home/rzai/prj/att-coref/cnn/cnn/tensor.h:21,
                 from /home/rzai/prj/att-coref/cnn/cnn/cnn.h:13,
                 from /home/rzai/prj/att-coref/cnn/cnn/conv.h:4,
                 from /home/rzai/prj/att-coref/cnn/cnn/conv.cc:1:
/home/rzai/prj/eigen/Eigen/src/Core/util/Macros.h:252:35: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
 #define EIGEN_ASM_COMMENT(X)  asm("#"X)
                                   ^
In file included from /home/rzai/prj/att-coref/cnn/cnn/cnn.h:13:0,
                 from /home/rzai/prj/att-coref/cnn/cnn/cnn.cc:1:
/home/rzai/prj/att-coref/cnn/cnn/tensor.h:22:42: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory
 #include <unsupported/Eigen/CXX11/Tensor>
                                          ^
compilation terminated.
In file included from /home/rzai/prj/eigen/Eigen/Core:35:0,
                 from /home/rzai/prj/eigen/Eigen/Dense:1,
                 from /home/rzai/prj/eigen/Eigen/Eigen:1,
                 from /home/rzai/prj/att-coref/cnn/cnn/tensor.h:21,
                 from /home/rzai/prj/att-coref/cnn/cnn/cnn.h:13,
                 from /home/rzai/prj/att-coref/cnn/cnn/cfsm-builder.h:6,
                 from /home/rzai/prj/att-coref/cnn/cnn/cfsm-builder.cc:1:
/home/rzai/prj/eigen/Eigen/src/Core/util/Macros.h:252:35: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
 #define EIGEN_ASM_COMMENT(X)  asm("#"X)
                                   ^
In file included from /home/rzai/prj/eigen/Eigen/Core:35:0,
                 from /home/rzai/prj/eigen/Eigen/Dense:1,
                 from /home/rzai/prj/eigen/Eigen/Eigen:1,
                 from /home/rzai/prj/att-coref/cnn/cnn/tensor.h:21,
                 from /home/rzai/prj/att-coref/cnn/cnn/cnn.h:13,
                 from /home/rzai/prj/att-coref/cnn/cnn/cfsm-builder.h:6,
                 from /home/rzai/prj/att-coref/cnn/cnn/cfsm-builder.cc:1:
/home/rzai/prj/eigen/Eigen/src/Core/util/Macros.h:252:35: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
 #define EIGEN_ASM_COMMENT(X)  asm("#"X)
                                   ^
In file included from /home/rzai/prj/att-coref/cnn/cnn/cnn.h:13:0,
                 from /home/rzai/prj/att-coref/cnn/cnn/conv.h:4,
                 from /home/rzai/prj/att-coref/cnn/cnn/conv.cc:1:
/home/rzai/prj/att-coref/cnn/cnn/tensor.h:22:42: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory
 #include <unsupported/Eigen/CXX11/Tensor>
                                          ^
compilation terminated.
In file included from /home/rzai/prj/att-coref/cnn/cnn/cnn.h:13:0,
                 from /home/rzai/prj/att-coref/cnn/cnn/cfsm-builder.h:6,
                 from /home/rzai/prj/att-coref/cnn/cnn/cfsm-builder.cc:1:
/home/rzai/prj/att-coref/cnn/cnn/tensor.h:22:42: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory
 #include <unsupported/Eigen/CXX11/Tensor>
                                          ^
compilation terminated.
In file included from /home/rzai/prj/att-coref/cnn/cnn/cnn.h:13:0,
                 from /home/rzai/prj/att-coref/cnn/cnn/cfsm-builder.h:6,
                 from /home/rzai/prj/att-coref/cnn/cnn/cfsm-builder.cc:1:
/home/rzai/prj/att-coref/cnn/cnn/tensor.h:22:42: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory
 #include <unsupported/Eigen/CXX11/Tensor>
                                          ^
compilation terminated.
make[2]: *** [cnn/cnn/CMakeFiles/cnn.dir/conv.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  8%] Building CXX object cnn/cnn/CMakeFiles/cnn_shared.dir/cnn.cc.o
make[2]: *** [cnn/cnn/CMakeFiles/cnn.dir/cnn.cc.o] Error 1
[ 10%] make[2]: *** [cnn/cnn/CMakeFiles/cnn.dir/cfsm-builder.cc.o] Error 1
Building CXX object cnn/cnn/CMakeFiles/cnn_shared.dir/conv.cc.o
make[1]: *** [cnn/cnn/CMakeFiles/cnn.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 12%] Building CXX object cnn/cnn/CMakeFiles/cnn_shared.dir/deep-lstm.cc.o
make[2]: *** [cnn/cnn/CMakeFiles/cnn_shared.dir/cfsm-builder.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/rzai/prj/eigen/Eigen/Core:35:0,
                 from /home/rzai/prj/eigen/Eigen/Dense:1,
                 from /home/rzai/prj/eigen/Eigen/Eigen:1,
                 from /home/rzai/prj/att-coref/cnn/cnn/tensor.h:21,
                 from /home/rzai/prj/att-coref/cnn/cnn/cnn.h:13,
                 from /home/rzai/prj/att-coref/cnn/cnn/cnn.cc:1:
/home/rzai/prj/eigen/Eigen/src/Core/util/Macros.h:252:35: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
 #define EIGEN_ASM_COMMENT(X)  asm("#"X)
                                   ^
In file included from /home/rzai/prj/eigen/Eigen/Core:35:0,
                 from /home/rzai/prj/eigen/Eigen/Dense:1,
                 from /home/rzai/prj/eigen/Eigen/Eigen:1,
                 from /home/rzai/prj/att-coref/cnn/cnn/tensor.h:21,
                 from /home/rzai/prj/att-coref/cnn/cnn/cnn.h:13,
                 from /home/rzai/prj/att-coref/cnn/cnn/conv.h:4,
                 from /home/rzai/prj/att-coref/cnn/cnn/conv.cc:1:
/home/rzai/prj/eigen/Eigen/src/Core/util/Macros.h:252:35: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
 #define EIGEN_ASM_COMMENT(X)  asm("#"X)
                                   ^
In file included from /home/rzai/prj/att-coref/cnn/cnn/cnn.h:13:0,
                 from /home/rzai/prj/att-coref/cnn/cnn/cnn.cc:1:
/home/rzai/prj/att-coref/cnn/cnn/tensor.h:22:42: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory
 #include <unsupported/Eigen/CXX11/Tensor>
                                          ^
compilation terminated.
In file included from /home/rzai/prj/eigen/Eigen/Core:35:0,
                 from /home/rzai/prj/eigen/Eigen/Dense:1,
                 from /home/rzai/prj/eigen/Eigen/Eigen:1,
                 from /home/rzai/prj/att-coref/cnn/cnn/tensor.h:21,
                 from /home/rzai/prj/att-coref/cnn/cnn/cnn.h:13,
                 from /home/rzai/prj/att-coref/cnn/cnn/deep-lstm.h:4,
                 from /home/rzai/prj/att-coref/cnn/cnn/deep-lstm.cc:1:
/home/rzai/prj/eigen/Eigen/src/Core/util/Macros.h:252:35: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
 #define EIGEN_ASM_COMMENT(X)  asm("#"X)
                                   ^
In file included from /home/rzai/prj/att-coref/cnn/cnn/cnn.h:13:0,
                 from /home/rzai/prj/att-coref/cnn/cnn/conv.h:4,
                 from /home/rzai/prj/att-coref/cnn/cnn/conv.cc:1:
/home/rzai/prj/att-coref/cnn/cnn/tensor.h:22:42: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory
 #include <unsupported/Eigen/CXX11/Tensor>
                                          ^
compilation terminated.
In file included from /home/rzai/prj/att-coref/cnn/cnn/cnn.h:13:0,
                 from /home/rzai/prj/att-coref/cnn/cnn/deep-lstm.h:4,
                 from /home/rzai/prj/att-coref/cnn/cnn/deep-lstm.cc:1:
/home/rzai/prj/att-coref/cnn/cnn/tensor.h:22:42: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory
 #include <unsupported/Eigen/CXX11/Tensor>
                                          ^
compilation terminated.
make[2]: *** [cnn/cnn/CMakeFiles/cnn_shared.dir/cnn.cc.o] Error 1
make[2]: *** [cnn/cnn/CMakeFiles/cnn_shared.dir/conv.cc.o] Error 1
make[2]: *** [cnn/cnn/CMakeFiles/cnn_shared.dir/deep-lstm.cc.o] Error 1
make[1]: *** [cnn/cnn/CMakeFiles/cnn_shared.dir/all] Error 2
make: *** [all] Error 2
rzai@rzai00:~/prj/att-coref/build$

**Comment by miguelballesteros** [comment]
You need to 

git submodule init
git submodule update

mkdir build
cd build
cmake .. -DEIGEN3_INCLUDE_DIR=/path/to/eigen
make -j2

**But as I said, this code is not ready nor complete.** 

I compiled it now with boost 1.56 gcc 4.91 and hg clone https://bitbucket.org/eigen/eigen
